mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

spring:
  application.name: activity_management_system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/activity_management_system?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root

server:
  port: 9090


